import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SSRKeycloakProvider, SSRCookies } from "@react-keycloak/ssr"; // provides SSR context for keycloak because it's not available in the client

const KeycloakConfig = {
  realm: `${process.env.KEYCLOAK_REALM}` , 
  url: `${process.env.KEYCLOAK_URL}`, 
  clientId: `${process.env.REACT_AUTH_CLIENT_ID}`, 
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
    <SSRKeycloakProvider
      keycloakConfig={KeycloakConfig}
      init={true}
      initOnSSR={true}
      initOptions={{
        onLoad: 'login-required',
        checkLoginIframe: false,
        checkLoginIframeInterval: 5,
      }}
    >
        {children}
    </SSRKeycloakProvider>
        </body>
    </html>
  );
}
